drop table cascade constraints;
drop table cascade constraints;
drop table cascade constraints;
drop table cascade constraints;
drop table cascade constraints;
drop table cascade constraints;
drop table cascade constraints;
drop table cascade constraints;
drop table cascade constraints;
drop table TipoPessoa cascade constraints;
drop table MoradorDeRua cascade constraints;
drop table Alergias cascade constraints;
drop table Habilidades cascade constraints;
drop table Instituicao cascade constraints;
drop table TipoInstituicao cascade constraints;
drop table TipoEmpresa cascade constraints;
drop table Assessoria cascade constraints;
drop table Privada cascade constraints;
drop table Atendimento cascade constraints;
drop table Consulta cascade constraints;
drop table PontoDeColeta cascade constraints;
drop table Estoque cascade constraints;
drop table Produto cascade constraints;
drop table Alimento cascade constraints;
drop table Medicamento cascade constraints;
drop table FornecimentoProduto cascade constraints;
drop table DoacaoProduto cascade constraints;
drop table Doador cascade constraints;
drop table DoacaoFinanceira cascade constraints;
drop table Vestuario cascade constraints;
drop table TipoProduto Higiene cascade constraints;
drop table Dormitorio cascade constraints;
drop table Estadia cascade constraints;
drop table Oportunidade cascade constraints;
drop table Servico cascade constraints;